/**
 * PriorityBadge Component
 * Displays task priority with color coding following design system
 * Generated by GitHub Copilot using TaskFlow specifications
 */

import { TaskPriority } from '@/types';
import { getPriorityColor, getPriorityLabel } from '@/lib/utils';

export interface PriorityBadgeProps {
  priority: TaskPriority;
  size?: 'sm' | 'md' | 'lg';
}

/**
 * Priority badge component following TaskFlow design system
 * Displays priority level with appropriate color coding
 */
export function PriorityBadge({ priority, size = 'md' }: PriorityBadgeProps) {
  const colorClasses = getPriorityColor(priority);
  const label = getPriorityLabel(priority);
  
  const sizeClasses = {
    sm: 'text-xs px-2 py-1',
    md: 'text-sm px-3 py-1',
    lg: 'text-base px-4 py-2',
  };

  return (
    <span
      className={`
        inline-flex items-center rounded-full font-medium
        ${colorClasses}
        ${sizeClasses[size]}
      `}
      role="status"
      aria-label={`Priority: ${label}`}
    >
      {label}
    </span>
  );
}
